### ISSUE TITLE
안드로이드 킷캣에서 데이터를 불러오지 못함

### ISSUE THREAD

**Issue by kongwoojin** [kongwoojin/GGCJ#1]
안드로이드 킷캣(API 19)에서 교육청 서버에 접속하지 못하여 급식 및 학사일정 데이터를 불러오지 못합니다.
SSL 인증서 문제인것으로 추정됩니다.

**Comment by kongwoojin** [comment]
로그캣:
```
01-20 16:40:38.220 21732-26551/com.kongjak.ggcj W/System.err: org.hyunjun.school.SchoolException: 교육청 서버에 접속하지 못하였습니다.
01-20 16:40:38.220 21732-26551/com.kongjak.ggcj W/System.err:     at org.hyunjun.school.School.getContentFromUrl(School.java:169)
01-20 16:40:38.220 21732-26551/com.kongjak.ggcj W/System.err:     at org.hyunjun.school.School.getMonthlySchedule(School.java:138)
01-20 16:40:38.220 21732-26551/com.kongjak.ggcj W/System.err:     at com.kongjak.ggcj.Activity.MainActivity$2.run(MainActivity.java:161)
01-20 16:40:38.220 21732-26551/com.kongjak.ggcj W/System.err:     at java.lang.Thread.run(Thread.java:841)
```

**Comment by kongwoojin** [comment]
Android API Level 19 이하의 버전이 TLS 1.2를 기본적으로 지원하지 않아 발생하는 문제로 보입니다.
API 21(Lollipop)이후 버전은 정상적으로 작동합니다.

**Comment by kongwoojin** [comment]
NEIS Open API로 파싱하면서 수정됨.
